# Site settings
title: Junaid Masoodi - Front-End Developer
email: iam@junaidmasoodi.com
author: Junaid Masoodi
description: "Front-End developer"
baseurl: ""
url: "http://junaidmasoodi.com"

# Build settings
markdown: kramdown
permalink: pretty

# Gems
gems:
   - jekyll-sitemap
