# Site settings
title: Junaid Masoodi
email: iam@junaidmasoodi.com
description: "Amateur Front-End developer"
baseurl: ""
url: "http://junaidmasoodi.com"

# Build settings
markdown: kramdown
permalink: pretty
